### ISSUE TITLE
Cannot find module '../index'

### ISSUE THREAD

**Issue by AugustDG** [mbrandau/css-shortener#51]
Hey!

I was trying out this plugin, but couldn't use it as this error always came up:

```
Error: Cannot find module '../index'
Require stack:
- C:\Users\augus\AppData\Roaming\npm\node_modules\css-shortener\bin\cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\augus\AppData\Roaming\npm\node_modules\css-shortener\bin\cli.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\augus\\AppData\\Roaming\\npm\\node_modules\\css-shortener\\bin\\cli.js'
  ]
}
```

When I went to check the file, it indeed was requiring an '../index', but I couldn't find it either...

```
const CssShortener = require('../index');
const fs = require('fs');
```

**Comment by AugustDG** [comment]
Just replaced '../index' with 'css-shortener' and it works!
